imp CIP-1855: complement with CIP-0005 prefixes
cardano-foundation/CIPs pull request #194
Opened 2022-01-16 22:21 UTC by blaggacao

2022-01-16 22:33 UTC, disassembler requested changes

2022-01-16 22:33 UTC, disassembler commented on CIP-1855/README.md
> +- Contrary to CIP 1852, we don't use the `role` and `index` levels of the derivation path, since index is expressed ad the 3rd level and no roles for policy signing keys are currently anticipated.
Typo, at

2022-01-16 22:33 UTC, disassembler commented on CIP-1855/README.md
> +Forging tokens is derived from a script policy. The script policy includes hashes of keys needed to forge new tokens and must be witnessed by the keys with hashes listed.
This isn't quite accurate. It can require all keys in the policy, or it can have thresholds of number of keys, such as a 2/3 or 3/5 policy.

2022-01-18 17:00 UTC, disassembler approved these changes

2022-01-19 04:42 UTC, rvl approved these changes
LGTM

2022-01-19 09:28 UTC, merged