Create CIP 69? - Set minPoolCost to 0
cardano-foundation/CIPs pull request #358
Opened 2022-10-20 20:03 UTC by ADARobinHood

2022-10-20 20:42 UTC, kieransimkin commented
👍👍🏻👍🏼👍🏽👍🏾👍🏿

2022-10-24 19:51 UTC, rphair commented
@ADARobinHood as I just wrote in https://github.com/cardano-foundation/CIPs/pull/360#issuecomment-1289454182 (so I'm copying parts of the text) there's a lot of common ground between these 2 proposals as you've observed from the Cardano Forum thread where @TobiasFancee jumped in: https://forum.cardano.org/t/cip-69-set-minpoolcost-to-0/109309/37

So since the Discord has been used to the common ground between several PoS proposals including dynamically suggested variations (there were 3 or 4 already which had parameter variations like this, some even exactly the same) I would like to invite you to all the same places.  My apologies if you've already been there but I can't line up your name with any of the participants:

---

... nice to see this begin on the Cardano Forum with such enthusiastic discussion. I've recommended an upcoming Biweekly CIP Editors' meeting to have a scope of all CIPs with this theme (revisions to PoS rewards & incentives), since a few more of them including yours have come in recently. If such an agenda is confirmed I'll post it here.

The Discord where we have these meetings online ([invite](https://discord.gg/kyaTyzkBqd)) also has a `#...cip-0050...` channel which now includes multiple CIPs for PoS revisions (I've asked the admin to rename it more generally; hopefully will happen soon). I didn't see you there yet & it would be great to have you included in that discussion. It tends to have more detail & "brainstorming" than we ever see on the GitHub thread, and also more focused peer review than on the Cardano Forum. 😎

2022-10-24 20:02 UTC, rphair reviewed
BTW so we can review this properly, please rename the document currently at this pathname: `CIP 69? - Set minPoolCost to 0`
to: `README.md`
and move the file into a descriptively named subdirectory: preferably something short beginning with `CIP` but not using a number.

2022-10-25 08:53 UTC, rphair commented on CIP 69? - Set minPoolCost to 0
> +CIP 69?
In fact @ADARobinHood there is a direct naming collision with a previously written candidate https://github.com/cardano-foundation/CIPs/pull/321, so this number should be removed ASAP from all further communications about your own proposal 🤓 (cc @KtorZ I'll go to the Cardano Forum now & notify the participants there)

2022-10-25 08:56 UTC, rphair commented on CIP 69? - Set minPoolCost to 0
> +CIP 69?
https://forum.cardano.org/t/cip-69-set-minpoolcost-to-0/109309/42

2022-11-03 20:20 UTC, ADARobinHood reviewed
Formatting corrections

2022-11-03 20:27 UTC, ADARobinHood reviewed
Typo fix

2022-11-04 05:18 UTC, rphair commented on CIP 69? - Set minPoolCost to 0
> +CIP 69?
thanks for updates; resolving this conversation...

2022-11-04 05:18 UTC, rphair commented on CIP 69? - Set minPoolCost to 0
> +---
thanks for update; resolving this conversation

2022-11-08 15:41 UTC, KtorZ commented on CIP minPoolCost 0/README.md
> +## Effects:
```suggestion
### Effects:
```

2022-11-08 15:41 UTC, KtorZ commented on CIP minPoolCost 0/README.md
> +## Backwards Compatibility:
```suggestion
### Backwards Compatibility:
```

2022-11-08 15:41 UTC, KtorZ commented on CIP minPoolCost 0/README.md
> +## Research and References
```suggestion
### Research and References
```

2022-11-08 15:41 UTC, KtorZ commented on CIP minPoolCost 0/README.md
> +https://iohk.io/en/blog/posts/2020/11/13/the-general-perspective-on-staking-in-cardano/
```suggestion

## Path to Active

- [ ] Reach out to IOG's core engineering and research teams for feedback regarding the feasibility and soundness of this proposal. 

- [ ] Create a protocol parameter update
    - [ ] Build the raw transaction
    - [ ] Have genesis delegates (IOG, CF & Emurgo) sign the update 
    - [ ] Submit it to the network
    - [ ] Confirm the update is eventually live and adopted by the network 
```

2022-11-08 18:17 UTC, KtorZ commented
We discussed this proposal in today's editors meeting (number 57). As for other proposals regarding the reward sharing scheme or the ledger rule, the proposal shall be merged as `Proposed` (with the above addition) while the founding members work with the community on a framework to review and proceed with changes in those areas of the protocol (see discussion in the -- upcoming -- meeting notes)

2022-11-08 18:17 UTC, ADARobinHood reviewed
changes

2022-11-08 18:18 UTC, KtorZ requested changes

2022-11-08 18:18 UTC, KtorZ commented on CIP minPoolCost 0/README.md
> +Status: Draft
```suggestion
Status: Proposed
```

2022-11-08 18:19 UTC, ADARobinHood reviewed
+

2022-11-08 18:22 UTC, KtorZ approved these changes

2022-11-08 18:22 UTC, KtorZ commented
(@ADARobinHood can you also adjust the folder name to 'CIP-0073' 🙏)

2022-11-09 06:04 UTC, rphair approved these changes
All in order as per yesterday's CIP meeting resolution & the new Path to Active.

2022-11-09 06:07 UTC, merged