Staking key chain for HD wallets
cardano-foundation/CIPs pull request #37
Opened 2020-11-04 09:48 UTC by SebastienGllmt

As per our discussion during the CIP call, I split up https://github.com/cardano-foundation/CIPs/pull/33 into two CIPs. This CIP contains the description of `chain=2` whereas CIP1852 now outlines the derivation strategy and acts as a registry of chain types.

2020-12-01 09:20 UTC, KtorZ commented on StakingKey/README.md
> +Wallets that use multiple staking keys are REQUIRED to use sequential indexing with no gaps. This is to make detection of mangle addresses (addresses where the payment key belongs to the user, but th
*the detection of mangle addresses **possible** (

I imagine.

2020-12-01 09:21 UTC, KtorZ approved these changes

2020-12-07 17:38 UTC, crptmppt commented
can we change the structure to match the new repo format (so Github can display appropriately)?

2020-12-09 11:47 UTC, crptmppt requested changes

2020-12-09 11:47 UTC, crptmppt commented on CIP-0011/CIP-0011.md
> +Starting with the Shelley hardfork, Cardano makes use of both the *UTXO model* and the *account model*. To support both transaction models from the same master key, we allocate a new chain for [CIP18
need to change link to `../CIP-1852`

2020-12-09 11:47 UTC, crptmppt commented on CIP-0011/CIP-0011.md
> +Recall that [CIP1852](../CIP1852) specifies the following derivation path
need to change link to ../CIP-1852

2020-12-11 12:21 UTC, crptmppt approved these changes
will add pr for link fixes

2020-12-11 12:21 UTC, merged