Update CIP-0015.md
cardano-foundation/CIPs pull request #71
Opened 2021-03-06 10:42 UTC by disassembler

Updates CIP to match implementation. It's not the vote pubkey that signed, but the entire vote payload.

2021-03-06 10:46 UTC, SebastienGllmt commented
Would be great if we can also add a test vector

2021-03-30 08:44 UTC, SebastienGllmt requested changes
Needs to be updated for fund4

2021-04-09 00:12 UTC, SebastienGllmt approved these changes

2021-04-13 09:07 UTC, SebastienGllmt requested changes

2021-04-13 09:07 UTC, SebastienGllmt commented on CIP-0015/CIP-0015.md
> +Signing the voting registration with the staking private key. The voting registration payload is the CBOR encoded metadata including the 61284 key in binary format.
Change this PR to avoid modifying CIP15 itself. Only the test vector

2021-04-13 09:11 UTC, dcoutts approved these changes
As @SebastienGllmt says, we need to change this PR to avoid modifying CIP15 itself, and only change the test vectors. So this is good to go once that's done.

2021-04-27 08:47 UTC, SebastienGllmt approved these changes

2021-04-27 08:48 UTC, KtorZ approved these changes
LGTM

2021-04-27 08:50 UTC, merged